version: '3'
services:
  node-app:
    build: .
    volumes:
      - /app/node_modules
      - .:/app
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    volumes:
      - /app/build:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app