sudo: required
services:
  - docker

before_install:
  - docker build -t pavankumarbvrm/docker-in-action

script:
  - docker run pavankumarbvrm/docker-in-action npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-app"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-146925783396"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
